### PR TITLE
add prototype birdlife script

### PR DESCRIPTION
**Pull request by davharris**

### CODE REVIEW

**Comment by sckott** [comment]
@davharris looks like you forgot to include those files https://travis-ci.org/ropensci/traits/builds/51551190#L1392

**Comment by davharris** [comment]
I'm still not sure if I can distribute the files.  I'll remove the dependency on them.  Sorry for the confusion.

**Comment by sckott** [comment]
ah, ok, forgot about that

**Comment by davharris** [comment]
Rereading this, it looks more like a one-off *script*, rather than a set of reusable functions.

I could modify them to be more general, but probably not today.  Still interested?

**Comment by sckott** [comment]
Yes, still interested

**Comment by sckott** [comment]
@davharris hi dave, what's the status on this?  should I close this? or plans to push new commits to this PR?

**Comment by davharris** [comment]
Hi Scott, sorry I forgot about this. I'll try to get to it this weekend.

**Comment by sckott** [comment]
thanks @davharris

**Comment by davharris** [comment]
The new version of this code should work.  I added some simple documentation and ran `devtools::check`.  I'd still like to get some of the other data, though (countries, IUCN RedList status, threat list, migratory status, forest dependency, population trend...).

The threats list is especially interesting, but also especially tricky in terms of formatting ([example](http://www.birdlife.org/datazone/species/factsheet/22726874/additional)).

**Comment by sckott** [comment]
nice! thanks @davharris - small request - can we rename `get_birdlife_habitat` to `birdlife_habitat` or something else, impt part that starts with `birdlife`? Cause trying to give users an indication right off the bat of what data source they are getting data from

**Comment by davharris** [comment]
Absolutely.

I also figured out how to get some of the "threats" data into a usable form.  Should that go into the same function (so that we only have to download the data once) or into its own function (so that each function returns a simpler output?

**Comment by sckott** [comment]
Great, thanks. 

Simpler is better I think.

**Comment by davharris** [comment]
All set.  Will set up a separate pull request for a threats function shortly.

**Comment by sckott** [comment]
thanks!

**Pull request merged**
