### PR TITLE
Add url parameter to betydb functions

### LINKED ISSUE #74: How can I make url an optional parameter in betydb_* functions?
On line 159 of [R/betydb.R](https://github.com/ropensci/traits/blob/master/R/betydb.R#L159) there is a helper function `betyurl <- function() 'https://www.betydb.org/'`

However, BETYdb is a federated network of databases, betydb.org was the first, and all of the instances sync their public data (so this is a good default) but we need the ability to specify the url.

I'd like to add `url` as an argument to each function call, or perhaps use the `options()` function to set this parameter. What is the best way to do this - e.g. by changing `betyurl` or `bety_GET` or otherwise ... advice appreciated.

@sckott ?

### PR DESCRIPTION
**Pull request by dlebauer**
Fixes #74

### CODE REVIEW

**Comment by dlebauer** [comment]
@sckott or whomever reviews this ... while you are reviewing it any thoughts on refactoring would be welcome, as we will likely do this to support our new API in the next few months. My primary

**Comment by sckott** [comment]
> My primary

@dlebauer looks like you meant to finish saying something?

**Comment by sckott** [comment]
@dlebauer looks good to me, let me know on the above comment if you had something else you wanted to say

**Comment by dlebauer** [comment]
@sckott The question trailed off (accidentally). I was looking for more information about some of the lower level functions (betydb_get, _http, _auth). But I was able to figure it out by looking at the code (kudos for writing internal functions that are understandable without documentation) and documentation of functions that these functions call. 

In conclusion - this can be merged and closed. - Thanks

**Pull request merged**
