### PR TITLE
fix issue with web scraping + better naming

### PR DESCRIPTION
**Pull request by ibartomeus**
I fixed an issue in fe_native when the plant is present in fe, but with no distribution. Now it warns you instead of crashing. I also updated a message in is_native to be more clear.

### CODE REVIEW

**Comment by sckott** [comment]
@ibartomeus nice, thanks!

Looks like you were behind a bit 

screen shot 2015-09-17 at 10 12 03 am

can you merge changes from master from this repo on to your master branch, hopefully there won't be conflicts

**Comment by sckott** [comment]
@ibartomeus if it's too much to do, I can merge manually locally

**Comment by ibartomeus** [comment]
Scott, how can I update my fork to the current status on the original? I would like to learn this!

**Comment by sckott** [comment]
Typically, this is done via setting the upstream URL in your repo locally on your machine (if you haven't done this yet, it's of the form `git remote add upstream git@github.com:ropensci/traits.git` (or the https version if you're using that) 

Then doing `git pull upstream master` (or combination of `git fetch` and `git merge`) 

There probably will be conflicts that you'll have to deal with manually as I did update the files you changed in this PR recently, just minor changes I think

**Comment by ibartomeus** [comment]
I think I did it. Can you now accept the PR with no troubles? Thanks for the help, as always!

**Comment by sckott** [comment]
@ibartomeus looks good. 

glad to help

**Pull request merged**
